apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-webappone-deployment
  labels:
    app: tomcat-webappone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat-webappone
  template:
    metadata:
      labels:
        app: tomcat-webappone
    spec:
      containers:
      - name: tomcat-webappone
        image: iamdockeruser/tomcat-webappone:6
        resources:
          requests:
            cpu: "200m"
        ports:
        - containerPort: 8080
